module.exports = {
    camp: {/*image: 'camp.png',*/ topics: ['basic']},
    group: {/*image: 'group.png',*/ topics: ['basic', 'organisation']},


    scarf: {topics: ['basic']},
    course: {topics: ['basic']},
    badge: {topics: ['basic']},
    programme: {topics: ['basic']},


    worldmovement: {topics: ['organisation']},
    movement: {topics: ['organisation']},
    region: {topics: ['organisation']},
    district: {topics: ['organisation']},
    troop: {topics: ['organisation']},
    patrol: {topics: ['organisation']},
    troopleader: {topics: ['organisation']},
    patrolleader: {topics: ['organisation']},
    groupleader: {topics: ['organisation']},
    participant: {topics: ['organisation']},

    axe: {topics: ['equipment']},
    shovel: {topics: ['equipment']},
    saw: {topics: ['equipment']},
    rope: {topics: ['equipment']},
    carabiner: {topics: ['equipment']},
    pincers: {topics: ['equipment']},
    nail: {topics: ['equipment']},
    screw: {topics: ['equipment']},
    rasp: {topics: ['equipment']},
    drill: {topics: ['equipment']},

    mattress: {topics: ['equipment']},
    sleepingBag: {topics: ['equipment']},
    dayPack: {topics: ['equipment']},
    camppack: {topics: ['equipment']},
    matches: {topics: ['equipment']},
    string: {topics: ['equipment']},
    lamp: {topics: ['equipment']},

    overhand: {topics: ['knots']},
    noose: {topics: ['knots']},
    reefKnot: {topics: ['knots']},
    grannyKnot: {topics: ['knots']},
    doubleFisherman: {topics: ['knots']},
    bowline: {topics: ['knots']},
    sheetBend: {topics: ['knots']},
    figureEight: {topics: ['knots']},
    munterHitch: {topics: ['knots']},
    prusik: {topics: ['knots']},
    squareLashing: {topics: ['knots']},
    diagonalLashing: {topics: ['knots']},
};