module.exports = {
    camp: {topics: ['basic']},
    group: {topics: ['basic', 'organisation']},
    scarf: {topics: ['basic']},
    course: {topics: ['basic']},
    badge: {topics: ['basic']},
    programme: {topics: ['basic']},
    hike: {topics: ['basic']},
    campfire: {topics: ['basic']},
    hut: {topics: ['basic']},
    competition: {topics: ['basic']},

    worldmovement: {topics: ['organisation']},
    movement: {topics: ['organisation']},
    region: {topics: ['organisation']},
    district: {topics: ['organisation']},
    troop: {topics: ['organisation']},
    patrol: {topics: ['organisation']},

    troopleader: {image: true,topics: ['organisation']},
    patrolleader: {image: true,topics: ['organisation']},
    groupleader: {image: true,topics: ['organisation']},
    assistantleader: {topics: ['organisation']},
    participant: {topics: ['organisation']},
    quartermaster: {topics: ['organisation']},
    subcamp: {topics: ['organisation']},
    profBadge: {topics: ['organisation']},

    axe: {topics: ['equipment']},
    shovel: {topics: ['equipment']},
    lamp: {topics: ['equipment']},
    saw: {topics: ['equipment']},
    rope: {topics: ['equipment']},
    carabiner: {topics: ['equipment']},
    pincers: {topics: ['equipment']},
    screw: {topics: ['equipment']},
    rasp: {topics: ['equipment']},
    nail: {topics: ['equipment']},
    drill: {topics: ['equipment']},
    cord: {topics: ['equipment']},
    tent: {topics: ['equipment']},
    flag: {topics: ['equipment']},

    matches: {topics: ['equipment']},
    mattress: {topics: ['equipment']},
    sleepingBag: {topics: ['equipment']},
    dayPack: {topics: ['equipment']},
    camppack: {topics: ['equipment']},
    string: {topics: ['equipment']},
    gloves: {topics: ['equipment']},
    flashlight: {topics: ['equipment']},
    rubberBoots: {topics: ['equipment']},
    hikingBoots: {topics: ['equipment']},
    rainJacket: {topics: ['equipment']},
    anorak: {topics: ['equipment']},
    uniform: {topics: ['equipment']},
    knive: {topics: ['equipment', 'cooking']},
    fork: {topics: ['equipment', 'cooking']},
    spoon: {topics: ['equipment', 'cooking']},
    cutlery: {topics: ['equipment', 'cooking']},
    plate: {topics: ['equipment', 'cooking']},
    cup: {topics: ['equipment', 'cooking']},

    compass: {topics: ['orienteering']},
    map: {topics: ['orienteering']},
    coordinates: {topics: ['orienteering']},
    north: {topics: ['orienteering']},
    east: {topics: ['orienteering']},
    south: {topics: ['orienteering']},
    west: {topics: ['orienteering']},

    firstAid: {image: true, topics: ['firstAid']},
    help: {topics: ['firstAid']},
    doctor: {topics: ['firstAid']},
    medicine: {topics: ['firstAid']},
    hospital: {topics: ['firstAid']},
    wounded: {topics: ['firstAid']},
    cut: {topics: ['firstAid']},

    knot: {image: true, topics: ['knots']},
    overhand: {topics: ['knots']},
    noose: {topics: ['knots']},
    reefKnot: {topics: ['knots']},
    grannyKnot: {topics: ['knots']},
    doubleFisherman: {topics: ['knots']},
    bowline: {topics: ['knots']},
    sheetBend: {topics: ['knots']},
    figureEight: {topics: ['knots']},
    munterHitch: {topics: ['knots']},
    prusik: {topics: ['knots']},
    cowHitch: {topics: ['knots']},
    squareLashing: {topics: ['knots']},
    diagonalLashing: {topics: ['knots']},

    soccer: {topics: ['sports']},
    volley: {topics: ['sports']},
    floorball: {topics: ['sports']},
    rugby: {topics: ['sports']},
    basketball: {topics: ['sports']},
    baseball: {topics: ['sports']},
    badminton: {topics: ['sports']},
    handball: {topics: ['sports']},
    dancing: {topics: ['sports']},
    orienteeringSport: {topics: ['sports']},
    swimming: {topics: ['sports']},
    sled: {topics: ['sports']},
    ccSkiing: {topics: ['sports']},
    iceSkating: {topics: ['sports']},
    climbing: {topics: ['sports']},

    nature: {topics: ['nature']},
    animal: {topics: ['nature']},
    trace: {topics: ['nature']},
    plant: {topics: ['nature']},
    mushroom: {topics: ['nature']},
    weather: {topics: ['nature']},

    junds: {topics: ['junds']},
    campactivity: {topics: ['junds']},
    campsport: {topics: ['junds']},
    course1: {image: true, topics: ['junds']},
    course2: {image: true, topics: ['junds']},
    courseRep: {topics: ['junds']},
    coach: {topics: ['junds']},
    youthSport: {topics: ['junds']},
    kidsSport: {topics: ['junds']},
    campLeader: {topics: ['junds']},
    expert: {topics: ['junds']},
    safety: {topics: ['junds']},
    manual: {topics: ['junds']},
    activity: {topics: ['junds']},
    goal: {topics: ['junds']},
    concept: {topics: ['junds']},
    planning: {topics: ['junds']},
    realisation: {topics: ['junds']},
    evaluation: {topics: ['junds']},
    campDossier: {topics: ['junds']},
    generalProgramme: {topics: ['junds']},
    youthOrganisation: {topics: ['junds']},
    mountains: {topics: ['junds']},
    winter: {topics: ['junds']},
    water: {topics: ['junds', 'cooking', 'nature']},
    emergencySheet: {topics: ['junds']},
};