module.exports = {
    basic: {title: 'Basic terms'},
    organisation: {title: 'Organisation'},
    equipment: {title: 'Equipment'},
    firstAid: {title: 'First Aid'},
    knots: {title: 'Knots'},
    nature: {title: 'Nature'},
    sportsGames: {title: 'Sports'},
    orienteering: {title: 'Orienteering'},
    cooking: {title: 'Cooking'},
    treehouse: {title: 'Treehouse building'},
    ch: {title: 'Switzerland'},
    junds: {title: 'Youth and Sports', hide: true},
    no: {title: 'Norway'},
    fi: {title: 'Finland'},
};